User controller
wolox-training/da-java pull request #8
Opened 2019-03-18 18:46 UTC by darwinaraqueo

**Summary**
Modification for user controller, this allow have rest controllers for use in cruds

**Trello Card**
(Go!)[https://trello.com/c/GjwPVfrj/22-crear-user-controller-con-las-operaciones-crud-de-user]

2019-03-18 20:10 UTC, zeminlu requested changes
Looks good, check my comments!

2019-03-18 20:10 UTC, zeminlu commented on src/main/java/wolox/training/controller/BookController.java
>  @Controller
We use RestController for an REST API app.

2019-03-18 20:10 UTC, zeminlu commented on src/main/java/wolox/training/controller/UserController.java
> +@Controller
We use RestController for an REST API app.

2019-03-18 20:10 UTC, zeminlu commented on src/main/java/wolox/training/exceptions/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
This would be a not found http return status code.

2019-03-18 21:51 UTC, darwinaraqueo commented on src/main/java/wolox/training/controller/BookController.java
>  @Controller
ready

2019-03-19 17:17 UTC, zeminlu approved these changes

2019-03-19 17:50 UTC, merged